// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Add.g.generated.h"

// Reducer arguments struct for Add
USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FAddArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString Name;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 Age;

    FAddArgs() = default;

    FAddArgs(const FString& InName, const int32& InAge)
        : Name(InName), Age(InAge)
    {}


    FORCEINLINE bool operator==(const FAddArgs& Other) const
    {
        return Name == Other.Name && Age == Other.Age;
    }
    FORCEINLINE bool operator!=(const FAddArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FAddArgs, Name, Age);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class CLIENT_UNREAL_API UAddReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString Name;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 Age;

};


