// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Debug.g.generated.h"

// Reducer arguments struct for Debug
USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FDebugArgs
{
    GENERATED_BODY()

    FDebugArgs() = default;


    FORCEINLINE bool operator==(const FDebugArgs& Other) const
    {
        return true;
    }
    FORCEINLINE bool operator!=(const FDebugArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT_EMPTY(FDebugArgs);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class CLIENT_UNREAL_API UDebugReducer : public UReducerBase
{
    GENERATED_BODY()

public:
};


