// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/PersonType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "PersonTable.g.generated.h"

UCLASS(Blueprintable)
class CLIENT_UNREAL_API UPersonIdUniqueIndex : public UObject
{
    GENERATED_BODY()

private:
    // Declare an instance of your templated helper.
    // It's private because the UObject wrapper will expose its functionality.
    FUniqueIndexHelper<FPersonType, int32, FTableCache<FPersonType>> IdIndexHelper;

public:
    UPersonIdUniqueIndex()
        // Initialize the helper with the specific unique index name
        : IdIndexHelper("Id") {
    }

    /**
     * Finds a Person by their unique id.
     * @param Key The id to search for.
     * @return The found FPersonType, or a default-constructed FPersonType if not found.
     */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB|PersonIndex")
    FPersonType Find(int32 Key)
    {
        // Simply delegate the call to the internal helper
        return IdIndexHelper.FindUniqueIndex(Key);
    }

    // A public setter to provide the cache to the helper after construction
    // This is a common pattern when the cache might be created or provided by another system.
    void SetCache(TSharedPtr<const FTableCache<FPersonType>> InPersonCache)
    {
        IdIndexHelper.Cache = InPersonCache;
    }
};
/***/

UCLASS(BlueprintType)
class CLIENT_UNREAL_API UPersonTable : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UPersonIdUniqueIndex* Id;

    void PostInitialize();

    /** Update function for Person table*/
    FTableAppliedDiff<FPersonType> Update(TArray<FWithBsatn<FPersonType>> InsertsRef, TArray<FWithBsatn<FPersonType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FPersonType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPersonInsert,
        const FEventContext&, Context,
        const FPersonType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnPersonUpdate,
        const FEventContext&, Context,
        const FPersonType&, OldRow,
        const FPersonType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnPersonDelete,
        const FEventContext&, Context,
        const FPersonType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPersonInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPersonUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnPersonDelete OnDelete;

private:
    const FString TableName = TEXT("Person");

    TSharedPtr<UClientCache<FPersonType>> Data;
};
