// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "PersonType.g.generated.h"

USTRUCT(BlueprintType)
struct CLIENT_UNREAL_API FPersonType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 Id;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Name;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 Age;

    FORCEINLINE bool operator==(const FPersonType& Other) const
    {
        return Id == Other.Id && Name == Other.Name && Age == Other.Age;
    }

    FORCEINLINE bool operator!=(const FPersonType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FPersonType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param PersonType The FPersonType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FPersonType& PersonType)
{
    uint32 Hash = GetTypeHash(PersonType.Id);
    Hash = HashCombine(Hash, GetTypeHash(PersonType.Name));
    Hash = HashCombine(Hash, GetTypeHash(PersonType.Age));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FPersonType);

    UE_SPACETIMEDB_STRUCT(FPersonType, Id, Name, Age);
}
